version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.openjdk.jmh:jmh-generator-annprocess
    versions:
    - "1.28"
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
